version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: newsdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      GNEWS_API_KEY: ${GNEWS_API_KEY}
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BASE_URL: "http://localhost:8080"
    environment:
      NEXT_PUBLIC_BASE_URL: "http://localhost:8080"
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata:
    external: true
    name: news_pgdata